import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  chatContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  chatHeader: {
    backgroundColor: '#4DA8DA',
    paddingTop: 10,
    paddingBottom: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  chatBackButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  chatAgentInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  chatAgentAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  chatAgentInitials: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  chatAgentDetails: {
    flex: 1,
  },
  chatAgentName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 2,
  },
  chatOnlineStatus: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  chatOnlineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#2ecc71',
    marginRight: 6,
  },
  chatOnlineText: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  chatThreadStatusBadge: {
    marginTop: 4,
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  chatThreadStatusText: {
    fontSize: 11,
    color: '#ffffff',
    fontWeight: '600',
  },
  chatResolveButton: {
    marginRight: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
  },
  chatResolveButtonText: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '600',
  },
  chatCallButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 20,
  },
  chatMessagesContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  chatMessagesContent: {
    flexGrow: 1,
    justifyContent: 'flex-end',
    padding: 16,
    paddingBottom: 20,
  },
  chatMessageBubble: {
    maxWidth: '80%',
    marginVertical: 4,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 18,
  },
  chatUserMessage: {
    alignSelf: 'flex-end',
    backgroundColor: '#4DA8DA',
    borderBottomRightRadius: 6,
  },
  chatAgentMessage: {
    alignSelf: 'flex-start',
    backgroundColor: '#ffffff',
    borderBottomLeftRadius: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  chatSystemMessageWrap: {
    alignSelf: 'center',
    backgroundColor: 'transparent',
    maxWidth: '92%',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  chatSystemMessageBubble: {
    alignSelf: 'center',
    backgroundColor: '#e9eef2',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chatSystemMessageText: {
    fontSize: 12,
    color: '#5c6c7a',
    textAlign: 'center',
    fontWeight: '500',
  },
  chatCallStartingBubble: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#dce6ec',
  },
  chatCallStartingText: {
    marginLeft: 8,
    fontSize: 13,
    color: '#48606f',
    fontWeight: '500',
  },
  chatSystemMessageTime: {
    marginTop: 4,
    textAlign: 'center',
    fontSize: 11,
    color: '#8b98a3',
  },
  chatMessageText: {
    fontSize: 16,
    lineHeight: 22,
    marginBottom: 4,
  },
  chatUserMessageText: {
    color: '#ffffff',
  },
  chatAgentMessageText: {
    color: '#2c3e50',
  },
  chatMessageTime: {
    fontSize: 12,
    opacity: 0.7,
  },
  chatUserMessageTime: {
    color: '#ffffff',
    textAlign: 'right',
  },
  chatAgentMessageTime: {
    color: '#7f8c8d',
  },
  chatTypingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
  },
  chatTypingText: {
    fontSize: 14,
    color: '#7f8c8d',
    fontStyle: 'italic',
    marginRight: 8,
  },
  chatTypingDots: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  chatTypingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#bdc3c7',
    marginHorizontal: 1,
  },
  chatQuickResponses: {
    backgroundColor: '#ffffff',
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#e1e8ed',
  },
  chatQuickResponsesContent: {
    paddingHorizontal: 16,
  },
  chatQuickResponseButton: {
    backgroundColor: '#f1f3f4',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#e1e8ed',
  },
  chatQuickResponseText: {
    fontSize: 14,
    color: '#4DA8DA',
    fontWeight: '500',
  },
  chatInputContainer: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderTopColor: '#e1e8ed',
  },
  chatInputWrapper: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: '#f8f9fa',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#e1e8ed',
  },
  chatInput: {
    flex: 1,
    fontSize: 16,
    color: '#2c3e50',
    maxHeight: 100,
    paddingVertical: 8,
    paddingRight: 12,
  },
  chatSendButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#bdc3c7',
  },
  chatSendButtonActive: {
    backgroundColor: '#4DA8DA',
  },
});
