import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // Full Screen Video Call Styles
  fullScreenVideoCall: {
    flex: 1,
    backgroundColor: '#000',
  },
  fullScreenVideoContainer: {
    flex: 1,
    position: 'relative',
  },
  fullScreenCameraView: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  fullScreenVideoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'space-between',
    padding: 24,
    paddingTop: 60,
    paddingBottom: 140, // Add more bottom padding to prevent overlap with controls
  },
  remoteVideoContainer: {
    position: 'absolute',
    top: 20,
    right: 20,
    width: 120,
    height: 160,
    backgroundColor: '#333',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 5,
    borderWidth: 2,
    borderColor: '#fff',
    overflow: 'hidden',
  },
  callHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  connectionStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  connectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#2ecc71',
    marginRight: 8,
  },
  connectionText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  flipCameraButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  agentInfo: {
    alignItems: 'center',
    marginTop: 40,
  },
  agentAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#3498db',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  agentInitials: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  agentName: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 4,
  },
  agentStatus: {
    color: '#ecf0f1',
    fontSize: 14,
  },
  videoCallControlsContainer: {
    position: 'absolute',
    bottom: 50, // Increase bottom margin
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    zIndex: 10, // Ensure controls are on top
  },
  videoCallControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    maxWidth: 280,
    alignSelf: 'center',
  },
  controlButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  endCallButton: {
    backgroundColor: '#e74c3c',
    width: 68,
    height: 68,
    borderRadius: 34,
    borderWidth: 0,
  },
  mutedButton: {
    backgroundColor: 'rgba(231, 76, 60, 0.8)',
  },
  videoOffButton: {
    backgroundColor: 'rgba(231, 76, 60, 0.8)',
  },

  // Service Modal Content Styles
  serviceContent: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  serviceIcon: {
    marginBottom: 24,
  },
  serviceDescription: {
    fontSize: 16,
    color: '#34495e',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 24,
    paddingHorizontal: 16,
  },
  permissionWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff3cd',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#ffeaa7',
  },
  permissionText: {
    marginLeft: 8,
    fontSize: 14,
    color: '#856404',
    fontWeight: '500',
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  statusLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#495057',
    marginRight: 8,
  },
  statusText: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  activeStatus: {
    color: '#28a745',
  },
  inactiveStatus: {
    color: '#6c757d',
  },
  actionButton: {
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 8,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 200,
  },
  startButton: {
    backgroundColor: '#2C3E50',
  },
  actionButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  serviceNote: {
    fontSize: 12,
    color: '#7f8c8d',
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 20,
    fontStyle: 'italic',
  },
});
