import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#0d1b2e' },
  scroll: { flex: 1 },
  content: { paddingHorizontal: 16, paddingBottom: 24 },
  header: {
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  brand: { fontSize: 13, fontWeight: '700', color: 'rgba(255,255,255,0.85)' },
  timeText: { fontSize: 12, color: '#6b7280' },
  monitoringBadge: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(34,197,94,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.3)',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    marginBottom: 14,
  },
  pulseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#22c55e',
  },
  monitoringBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#22c55e',
    letterSpacing: 0.4,
  },
  mapContainer: {
    backgroundColor: '#1a2a3d',
    borderRadius: 16,
    height: 160,
    marginBottom: 10,
    position: 'relative',
    overflow: 'hidden',
  },
  mapGrid: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.15,
    backgroundColor: '#1d6fa4',
  },
  mapRoute: {
    position: 'absolute',
    width: '70%',
    height: 3,
    backgroundColor: '#1d6fa4',
    borderRadius: 2,
    top: '50%',
    left: '15%',
  },
  mapDotStart: {
    position: 'absolute',
    width: 12,
    height: 12,
    backgroundColor: '#22c55e',
    borderRadius: 6,
    left: '14%',
    top: '50%',
    marginTop: -6,
    shadowColor: '#22c55e',
    shadowOpacity: 0.8,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 0 },
  },
  mapDotEnd: {
    position: 'absolute',
    width: 12,
    height: 12,
    backgroundColor: '#ef4444',
    borderRadius: 6,
    right: '14%',
    top: '50%',
    marginTop: -6,
  },
  mapUser: {
    position: 'absolute',
    width: 16,
    height: 16,
    backgroundColor: '#1d6fa4',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#fff',
    left: '48%',
    top: '50%',
    marginTop: -8,
  },
  mapLabel: {
    position: 'absolute',
    bottom: 8,
    right: 12,
    fontSize: 10,
    color: 'rgba(255,255,255,0.5)',
  },
  statsRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 10,
  },
  statCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  statValue: { fontSize: 16, fontWeight: '800', color: '#fff' },
  statLabel: {
    fontSize: 9,
    color: '#6b7280',
    marginTop: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  signalRow: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
  },
  signalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  signalTitle: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.7)',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  signalOk: { fontSize: 10, color: '#22c55e', fontWeight: '600' },
  signalItems: { flexDirection: 'row', gap: 6 },
  signalItem: {
    flex: 1,
    backgroundColor: 'rgba(34,197,94,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.2)',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 4,
    alignItems: 'center',
  },
  signalItemWarning: {
    backgroundColor: 'rgba(234,179,8,0.1)',
    borderColor: 'rgba(234,179,8,0.25)',
  },
  signalText: { fontSize: 9, color: '#22c55e', textAlign: 'center' },
  signalTextWarning: { color: '#eab308' },
  checkinBar: {
    backgroundColor: 'rgba(29,111,164,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(29,111,164,0.4)',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  checkinText: { fontSize: 11, color: 'rgba(255,255,255,0.85)' },
  checkinTime: { fontSize: 13, fontWeight: '700', color: '#1d6fa4' },
  endButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(239,68,68,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.3)',
    borderRadius: 12,
    paddingVertical: 12,
    marginBottom: 6,
  },
  endButtonText: { fontSize: 13, fontWeight: '700', color: '#ef4444' },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    paddingVertical: 10,
  },
  shareButtonText: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.55)',
  },
});
