import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#0d1b2e' },
  safe: { flex: 1 },
  body: {
    flex: 1,
    paddingHorizontal: 20,
    justifyContent: 'center',
  },
  shieldCircle: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(234,179,8,0.1)',
    borderWidth: 2,
    borderColor: 'rgba(234,179,8,0.3)',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  headline: {
    fontSize: 22,
    fontWeight: '800',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 8,
  },
  bodyText: {
    fontSize: 13,
    color: '#9ca3af',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  countdownCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'rgba(234,179,8,0.15)',
    borderWidth: 2,
    borderColor: '#eab308',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  countdownText: { fontSize: 22, fontWeight: '800', color: '#eab308' },
  safeButtonWrapper: {
    borderRadius: 14,
    marginBottom: 10,
    shadowColor: '#16a34a',
    shadowOpacity: 0.4,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  safeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
  },
  safeButtonText: { color: '#fff', fontSize: 15, fontWeight: '800' },
  helpButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(239,68,68,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.3)',
    borderRadius: 14,
    paddingVertical: 12,
    marginBottom: 10,
  },
  helpButtonText: { color: '#ef4444', fontSize: 13, fontWeight: '700' },
  extendButton: { alignItems: 'center', paddingVertical: 8 },
  extendText: { color: '#6b7280', fontSize: 12 },
});
