import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#1a0a0a' },
  header: { paddingHorizontal: 16, paddingBottom: 28 },
  headerContent: { alignItems: 'center', paddingTop: 12 },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
    marginTop: 6,
  },
  headerSub: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.75)',
    marginTop: 4,
  },
  scroll: { flex: 1, marginTop: -12 },
  scrollContent: { paddingHorizontal: 16, paddingBottom: 32 },
  stepsCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  stepsHeader: {
    fontSize: 11,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.55)',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.06)',
  },
  stepRowLast: { borderBottomWidth: 0, paddingBottom: 0 },
  stepNum: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  stepNumDone: {
    backgroundColor: 'rgba(34,197,94,0.2)',
    borderColor: 'rgba(34,197,94,0.35)',
  },
  stepNumActive: {
    backgroundColor: 'rgba(239,68,68,0.3)',
    borderColor: 'rgba(239,68,68,0.55)',
  },
  stepNumPending: {
    backgroundColor: 'rgba(107,114,128,0.2)',
    borderColor: 'rgba(107,114,128,0.25)',
  },
  stepNumText: { fontSize: 11, fontWeight: '700' },
  stepLabel: { fontSize: 12, fontWeight: '600', color: 'rgba(255,255,255,0.92)' },
  stepStatus: { fontSize: 10, color: '#9ca3af', marginTop: 2 },
  stepStatusActive: { color: '#ef4444' },
  safeButtonWrapper: {
    borderRadius: 14,
    marginBottom: 10,
    shadowColor: '#16a34a',
    shadowOpacity: 0.5,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  safeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
  },
  safeButtonText: { color: '#fff', fontSize: 15, fontWeight: '800' },
  socButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(239,68,68,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.4)',
    borderRadius: 14,
    paddingVertical: 12,
  },
  socButtonText: { color: '#ef4444', fontSize: 13, fontWeight: '700' },
  hint: {
    textAlign: 'center',
    fontSize: 10,
    color: '#6b7280',
    lineHeight: 16,
    marginTop: 12,
  },
});
