import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const passkeyModalStyles = StyleSheet.create({
  // Passkey Modal Styles
  passkeyOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  passkeyModal: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    width: width - 40,
    maxWidth: 400,
    maxHeight: '85%',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    shadowColor: 'rgba(0, 0, 0, 0.3)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
    overflow: 'hidden',
  },
  passkeyHeader: {
    alignItems: 'center',
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
  },
  passkeyTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#2c3e50',
    marginTop: 12,
    marginBottom: 8,
  },
  passkeySubtitle: {
    fontSize: 16,
    color: '#7f8c8d',
    textAlign: 'center',
  },
  passkeyContent: {
    padding: 24,
    paddingBottom: 32, // Extra padding at bottom for safe scrolling
  },
  
  // Emergency countdown styles for PasskeyModal
  emergencyCountdownContainer: {
    backgroundColor: 'rgba(204, 0, 34, 0.85)',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#CC0022',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
    overflow: 'hidden',
  },
  emergencyCountdownText: {
    color: '#ffffff',
    fontSize: 48,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  emergencyCountdownLabel: {
    color: '#ffffff',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 5,
  },
  
  passkeyLabel: {
    fontSize: 18,
    fontWeight: '500',
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 24,
  },
  passkeyInputContainer: {
    alignItems: 'center',
    marginBottom: 32,
  },
  passkeyDisplay: {
    flexDirection: 'row',
    gap: 16,
  },
  passkeyDigit: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderWidth: 2,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  passkeyDigitText: {
    fontSize: 24,
    fontWeight: '600',
    color: '#2c3e50',
  },
  passkeyKeypad: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 12,
    marginBottom: 24,
  },
  passkeyKey: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  passkeyKeyText: {
    fontSize: 24,
    fontWeight: '500',
    color: '#2c3e50',
  },
  passkeyActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    gap: 12,
  },
  passkeyDeleteButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  passkeyCancelButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: '#f8f9fa',
    borderWidth: 1,
    borderColor: '#dee2e6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  passkeyCancelText: {
    color: '#6c757d',
    fontSize: 16,
    fontWeight: '500',
  },
  passkeySubmitButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 25,
    minWidth: 120,
    alignItems: 'center',
  },
  passkeySubmitButtonActive: {
    backgroundColor: '#1f2937',
  },
  passkeySubmitText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  passkeyDemo: {
    alignItems: 'center',
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.2)',
  },
  passkeyDemoText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3b82f6',
    marginBottom: 4,
  },
  passkeyTimeout: {
    fontSize: 14,
    color: '#7f8c8d',
  },
  passkeyDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#bdc3c7',
    marginHorizontal: 4,
  },
  passkeyDotFilled: {
    backgroundColor: '#2c3e50',
  },
  passkeyKeyButton: {
    backgroundColor: '#ecf0f1',
    padding: 16,
    borderRadius: 8,
    margin: 4,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 60,
  },
});

